name: Backlog Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12 PM (noon) UTC, which is 4 AM PST
jobs:
  prune:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    permissions:
      # contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    name: Issue and PR
    steps:
      - name: Prune stale issues
        uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 375 # 1 year
          days-before-close: 30 # 1 month
          stale-issue-label: stale
          exempt-issue-labels: help wanted
          exempt-pr-labels: external-dependency
          stale-issue-message: >
            This issue has been inactive for a while, so it's
            been marked as "stale." If you're still working on
            it or it's still important, please leave a comment
            to keep it open and remove the "stale" label. Thanks!
          stale-pr-message: >
            This pull request hasn't had any recent activity,
            so it's been marked as "stale."  If you're still
            working on it or if it's still important, just keep
            making commits (code changes) and remove the "stale"
            label. Thanks!
          close-issue-message: >
            This issue has been automatically closed because
            there hasn't been any recent activity. If it's
            still relevant, please feel free to reopen it.
          close-pr-message: >
            This pull request has been automatically closed due
            to inactivity. If it's still relevant, please
            feel free to reopen it.
