# SPDX-License-Identifier: Apache-2.0
# Hyperledger Repolinter Action

name: Repolinter

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    container: ghcr.io/todogroup/repolinter:v0.10.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lint Repo
        continue-on-error: true
        run: bundle exec /app/bin/repolinter.js --rulesetUrl https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/master/repo_structure/repolint.json --format markdown | tee /repolinter-report.md
      - name: Save repolinter-report file
        uses: actions/upload-artifact@v3
        with:
          name: repolinter-report
          path: /repolinter-report.md
